#!/bin/bash

# Create a memory file system image and compare it to the one we are currently using, update if required
# The memory file is a FAT followed by non compressed files, use "hexdump -C page.mpfs |more" to see


CH=$1
if [ "$CH" == "" ]; then
        exit 1
fi



FSDIR="www"
#make a list of files and sizes in www
ls -1 "$FSDIR" >/tmp/list
echo "update_memoryfs:"

XC=0
echo "<pre>" >$FSDIR/list
while read p; do
        SIZE=`stat --printf="%s" $FSDIR/$p`
        echo -ne "<a href=$p>" >>$FSDIR/list
	echo -n "$XC" >>$FSDIR/list
	echo -e "\t$SIZE\t$p</a>" >>$FSDIR/list
	(( XC++ ))
done </tmp/list
echo "</pre>" >>$FSDIR/list

if [ -f "$FSDIR/A_DO_NOT_EDIT_THESE_FILE_USE_MAKEWWW" ]; then
	rm "$FSDIR/A_DO_NOT_EDIT_THESE_FILE_USE_MAKEWWW"
fi


# Now generate current set of files, this is still quick compared to flashing them into the esp module
./tools/mfsmaker $FSDIR page.mpfs
CMD="mv mfs_filecount.h include/"
echo $CMD
`$CMD`

echo -n "Memory File system image size is "
ls -lh page.mpfs |cut -d' ' -f5


CMD="mv page.mpfs $1/"
echo $CMD
`$CMD`

echo "" > "$FSDIR/A_DO_NOT_EDIT_THESE_FILE_USE_MAKEWWW"
