/* Header file generated by fdesign on Fri Oct  9 09:54:01 2020 */

#include <forms.h>


void terminalform_timer_cb( FL_OBJECT *, long );
void terminput_cb( FL_OBJECT *, long );
void termlauncher_cb( FL_OBJECT * obj, long data );


/* Forms and Objects */
typedef struct {
    FL_FORM   * form_terminal;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * form_terminal_timer;
    FL_OBJECT * termtext;

    FL_OBJECT * termlauncher;
    FL_OBJECT * terminput;
} FD_form_terminal;


FD_form_terminal * form_terminal_create( int aw, int ah );



