/* Header file generated by fdesign on Sat Nov 15 12:48:16 2014 */

#ifndef FD_mainform_h_
#define FD_mainform_h_

#include <forms.h>

void tabs_cb( FL_OBJECT *, long );
void preset_down_btn_cb( FL_OBJECT *, long );
void preset_up_btn_cb( FL_OBJECT *, long );
void button_save_cb( FL_OBJECT *, long );


/* Forms and Objects */

typedef struct {
    FL_FORM   * mainform;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * led;
    FL_OBJECT * sometext;
    //FL_OBJECT * preset_down_btn;
    //FL_OBJECT * preset_up_btn;
    FL_OBJECT * preset_label;
    //FL_OBJECT * button_save;
    FL_OBJECT * tabs;
} FD_mainform;

FD_mainform * create_form_mainform( void );

#endif /* FD_mainform_h_ */



